### ISSUE TITLE
双向绑定功能无法实现

### ISSUE THREAD

**Issue by HaonanQiu** [hellowoody/web-lesson#2]
![image](https://user-images.githubusercontent.com/76943289/103523424-c91bf880-4eb6-11eb-8769-253965a77520.png)
![image](https://user-images.githubusercontent.com/76943289/103523457-d507ba80-4eb6-11eb-96b9-6684856e7c24.png)
![image](https://user-images.githubusercontent.com/76943289/103523492-e0f37c80-4eb6-11eb-8721-930dc08ec1bd.png)
![image](https://user-images.githubusercontent.com/76943289/103523505-e6e95d80-4eb6-11eb-904f-32d807aac879.png)
按钮可以实现修改
但是输入框中修改文本，不会实现同步修改

**Comment by HaonanQiu** [comment]
已解决！基本库版本需要2.9.3以上

**Comment by hellowoody** [comment]
ok
